### PR TITLE
Removal of the Ersilia Current command

### PR DESCRIPTION
**Pull request by Ajoke23**
Thank you for taking your time to contribute to Ersilia, just a few checks before we proceed
- [x] Have you followed the guidelines in our [Contribution Guide](https://github.com/ersilia-os/ersilia/blob/master/CONTRIBUTING.md)
- [ ] Have you written new tests for your core changes, as applicable?
- [x] Have you successfully ran tests with your changes locally?

**Description**

Remove the Ersilia current command

**Changes to be made**
- Deleting of the current command line i.e `cmd.current()`
- Removal the cmd function which is the command implememtation code in 
**Status**

**To do**
None

Related to #1267

### CODE REVIEW

**Comment by Ajoke23** [comment]
@DhanshreeA I will be expecting your feedback

**Comment by P-Mefut** [comment]
hi @Ajoke23, looks good but we still have a def for current in the cmd.py files

`
    def current(self):
        m = importlib.import_module("ersilia.cli.commands.current")
        m.current_cmd()
`


that's line 32 - 34 which should be removed if your taking out the command

**Comment by Ajoke23** [comment]
Hi @DhanshreeA I tested the code locally and the result shows that current command has been successfully removed
removal of current command

**Comment by Ajoke23** [comment]
> hi @Ajoke23, looks good but we still have a def for current in the cmd.py files
> 
> `def current(self): m = importlib.import_module("ersilia.cli.commands.current") m.current_cmd()`
> 
> that's line 32 - 34 which should be removed if your taking out the command

Thanks for the suggestion.

**Comment by adebisi4145** [comment]
@Ajoke23 since you opened another PR, can you confirm we can close this then?

**Comment by dzumii** [comment]
Hello @Ajoke23, I can see you already created another pull request [here](https://github.com/ersilia-os/ersilia/pull/1284), can you confirm we can disregard and close this then?

**Comment by Ajoke23** [comment]
> Hello @Ajoke23, I can see you already created another pull request [here](https://github.com/ersilia-os/ersilia/pull/1284), can you confirm we can disregard and close this then?

Yes, you can close this particular pull request #1282

**Pull request closed without merging**
