### PR TITLE
Migrate setup to poetry

### PR DESCRIPTION
**Pull request by DhanshreeA**
- [x] Added `pyproject.toml` to mimic setup in setup.py
- [x] Updated tag to version workflow to auto update version in pyproject.toml
- [x] Updated python publish workflow to build with poetry instead of setup.py. By default poetry builds both source and binary distributions (I think I need to update the python image used in this workflow to actually contain poetry :sweat_smile: )

### CODE REVIEW

**Comment by miquelduranfrigola** [comment]
Hi @DhanshreeA I see workflows crashing - most notably, the json syntax checker. Any idea? I have limited bandwidth today to check

**Comment by GemmaTuron** [comment]
This PR #793 is also failing the syntax check for the installs.yml file  - I see your latest push @miquelduranfrigola did changes to the file, I'll try to amend it

**Comment by GemmaTuron** [comment]
@DhanshreeA 

Can you correct the `installs.yml` file in your branch? It won't pass the test otherwise. The right version is now on `main`

**Comment by DhanshreeA** [comment]
Currently stuck at figuring out why bentoml installation is not working within tests. :sweat_smile:

**Comment by DhanshreeA** [comment]
@miquelduranfrigola @GemmaTuron this is fixed, and ready for review.

**Review by miquelduranfrigola — COMMENTED** [review]
This looks good to me.

Let's give it a try!

**Pull request merged**
