### PR TITLE
Convert Airtable models to a JSON file 

### PR DESCRIPTION
**Pull request by carcablop**
Reference to issue https://github.com/ersilia-os/ersilia/issues/768 :

Creating a cron that downloads from Airtable models and saves them to a JSON file and uploads them to s3.
Creating a class that allows you to interact with S3 to get the JSON file and interact only with the models.json file.

### CODE REVIEW

**Comment by carcablop** [comment]
I am working on fixing the errors.

**Comment by miquelduranfrigola** [comment]
Hello @carcablop - should I merge the PR or should I wait? Thankyou!

**Comment by carcablop** [comment]
> Hola @carcablop- ¿Debería fusionar el PR o debería esperar? ¡Gracias!

Please don't merge. I'll let you know when I fix the errors. Thanks you so much.

**Comment by carcablop** [comment]
Hi @miquelduranfrigola and @DhanshreeA 
It is ready to merge.
In the last meeting Miquel shared with me the Airtable api key to run locally and although Miquel granted read and write permissions, I still have permission problems to run it from my local. In any case, there are no issues.
I have resolved some conflict problems between branches and I think we can merge to check that the data from the airtable models (model.json) is being loaded to S3.
Let me know if you find anything I should fix or take into account before merging the changes.
Thanks

**Comment by miquelduranfrigola** [comment]
Hello @carcablop - it still gives an error: https://github.com/ersilia-os/ersilia/actions/runs/8554088737/job/23438639734

**Comment by DhanshreeA** [comment]
Not sure why that error is coming up because I do see a models.json within that S3 bucket.

**Comment by miquelduranfrigola** [comment]
I've added the `models.json` file manually - I don't think it was there.

**Comment by carcablop** [comment]
Thanks @miquelduranfrigola and @DhanshreeA . Apologies and thanks for the above.
The error is due to the access credentials, in this case, the "key".
My error is here:, when I get the access keys: [`${{ secrets.AWS_ACCESS_KEY_ID }}`](https://github.com/ersilia-os/ersilia/blob/master/.github/workflows/airtable_to_json.yml#L28) I wrote it wrong and it should be like this: `${{ secrets.AWS_ACCESS_KEY }}`.
Let me correct it and commit the changes again.

**Pull request merged**
