### PR TITLE
Fixed typos in Outreachy-Winter-2023 guidelines

### PR DESCRIPTION
**Pull request by PromiseFru**

### CODE REVIEW

**Comment by carcablop** [comment]
Hello @PromiseFru 
Thank you very much for your contribution, I have seen that some are spelling errors, other words are not errors, such as:

- fulfills" (with a double "l") and "fulfils" (with a single "l") may depend on the variant of English you are using.
- Specially or Especially, both are possible.
- continuously or continually, are also valid.

Python version 3.7 is valid for Ersilia.

**Comment by PromiseFru** [comment]
> Hello @PromiseFru Thank you very much for your contribution, I have seen that some are spelling errors, other words are not errors, such as:
> 
>     * fulfills" (with a double "l") and "fulfils" (with a single "l") may depend on the variant of English you are using.
> 
>     * Specially or Especially, both are possible.
> 
>     * continuously or continually, are also valid.
> 
> 
> Python version 3.7 is valid for Ersilia.

Hello @carcablop,

I appreciate your feedback. I will incorporate the changes you've suggested into the PR. If you come across any more issues with the update, please let me know 🙏🏾

**Comment by GemmaTuron** [comment]
Hi @PromiseFru 

Thanks for the review. Many of the changes you suggest simply depend on the English (UK or US) used, and as most of ersilia's contributors are not native english speakers, some expressions might sound a bit different than what you are used to. I'll correct the typos in the repo directly, but we prefer to leave the particularities and uniqueness of the english flavour our contributors have-

**Comment by PromiseFru** [comment]
> Hi @PromiseFru
> 
> Thanks for the review. Many of the changes you suggest simply depend on the English (UK or US) used, and as most of ersilia's contributors are not native english speakers, some expressions might sound a bit different than what you are used to. I'll correct the typos in the repo directly, but we prefer to leave the particularities and uniqueness of the english flavour our contributors have-

Hello @GemmaTuron,

Thank you for your response ❤️

**Pull request closed without merging**
