### PR TITLE
Ersilia outreachy

### PR DESCRIPTION
**Pull request by martwebber**
Hello @GemmaTuron, I have added a readme file. I'll continue making improvements. Your feedback will be highly appreciated.

### CODE REVIEW

**Review by GemmaTuron — CHANGES_REQUESTED** [review]
Hello @martwebber 

The ReadMe file is good, but you added it before the documentation folder was created by @Rufaida98 and there is a conflict now because git is trying to create a second folder also named documentation. 
Can you save your file somewhere, pull rebase the branch and add it to the /documentation folder that is already created?

**Review by GemmaTuron — APPROVED** [review]
This contribution will create a /documentation folder and add the first readme file proposed by a candidate

**Comment by GemmaTuron** [comment]
Hello @martwebber 
Thanks for the contribution.

**Comment by martwebber** [comment]
Thanks a lot for the feedback @GemmaTuron

**Pull request merged**
