### PR TITLE
Proper logging across multiple modules

### PR DESCRIPTION
**Pull request by MissTife**
Thank you for taking your time to contribute to Ersilia, just a few checks before we proceed
- [ ] Have you followed the guidelines in our [Contribution Guide](https://github.com/ersilia-os/ersilia/blob/master/CONTRIBUTING.md)
- [ ] Have you written new tests for your core changes, as applicable?
- [ ] Have you successfully ran tests with your changes locally?

**Description**
This Pull request replaces all print statements with appropriate logger calls across various modules, within the Ersilia project. The changes affect functions that report errors, debugging information, and other feedback.

**Changes to be made**
Introduced logging module across the following files:
bentoml.py,samplers.py, managers.py, search.py, test.py, cron.py, docker.py, issue_reporting.py, and conda_env_resolve.py

**Status**

_Replace this line with what you have done so far..._
Removed print statements and replaced them with logger methods (e.g., logger.info(), logger.error()).

**To do**

Ready for review

Is this pull request related to any open issue? If yes, replace issueID below with the issue ID

Related to #15

### CODE REVIEW

**Comment by dzumii** [comment]
Hello @MissTife can you indicate which issue this PR is related to? We dont have an issue #15 opened

**Comment by MissTife** [comment]
> Hello @MissTife can you indicate which issue this PR is related to? 
Here is the link to it .
https://github.com/ersilia-os/ersilia/pull/1302

**Comment by dzumii** [comment]
> > Hello @MissTife can you indicate which issue this PR is related to?
> > Here is the link to it .
> > #1302

This link leads to your PR. You need to link it to your assigned issue instead.

**Comment by dzumii** [comment]
@MissTife,since your [task](https://github.com/ersilia-os/ersilia-pack/issues/15) is to use the native logging library from Python to replace all the prints commands with a logger in the ersilia pack codebase, i think you are supposed to be making the changes and a PR to that repo not ersilia-os?

**Pull request closed without merging**
