### PR TITLE
anshu_windows.md

### PR DESCRIPTION
**Pull request by AnshuKumari197**
I created a tutorial video for how to use ersilia model hub.

### CODE REVIEW

**Comment by AnshuKumari197** [comment]
@GemmaTuron please merge it. I made a tutorial video for how to use ersillia model hub with lots of efforts.

**Comment by AnshuKumari197** [comment]
@miquelduranfrigola please merge my commit.

**Comment by miquelduranfrigola** [comment]
@GemmaTuron can you please check?

**Comment by miquelduranfrigola** [comment]
@GemmaTuron I am closing this. Thanks @AnshuKumari197 for the contribution - the link to the video is well noted and was used in assessing the applications.

**Pull request closed without merging**
