### PR TITLE
Added tests for CatalogTable.as_list_of_dicts (#1319)

### PR DESCRIPTION
**Pull request by daud99**
* Implemented test case with empty and standard input.

Thank you for taking your time to contribute to Ersilia, just a few checks before we proceed
- [x] Have you followed the guidelines in our [Contribution Guide](https://github.com/ersilia-os/ersilia/blob/master/CONTRIBUTING.md)
- [x] Have you written new tests for your core changes, as applicable?
- [x] Have you successfully ran tests with your changes locally?

Related to #1319

### CODE REVIEW

**Comment by daud99** [comment]
@DhanshreeA 

Let me know if I over did it. I have change input structure and made the needed changes so that nothing gets break.

Looking forward to your feedback.

**Comment by DhanshreeA** [comment]
> @DhanshreeA
> 
> For some reason, when I run the test cases on my local setup these two test cases gets fail.I'm sure why I haven't changed anything in the code which effect this part of the code. Can you see why is this?
> 
> ```
> ================================================================================================== ERRORS ==================================================================================================
> ________________________________________________________________________________ ERROR at setup of test_benchmark_original _________________________________________________________________________________
> file /Users/daudahmed/Outreachy/ERSILIA/ersilia/test/test_url_search.py, line 77
>   def test_benchmark_original(actual_url, benchmark, original_finder):
> E       fixture 'benchmark' not found
> >       available fixtures: actual_url, cache, capfd, capfdbinary, caplog, capsys, capsysbinary, doctest_namespace, monkeypatch, optimized_finder, original_finder, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory
> >       use 'pytest --fixtures [testpath]' for help on them.
> 
> /Users/daudahmed/Outreachy/ERSILIA/ersilia/test/test_url_search.py:77
> ________________________________________________________________________________ ERROR at setup of test_benchmark_optimized ________________________________________________________________________________
> file /Users/daudahmed/Outreachy/ERSILIA/ersilia/test/test_url_search.py, line 82
>   def test_benchmark_optimized(actual_url, benchmark, optimized_finder):
> E       fixture 'benchmark' not found
> >       available fixtures: actual_url, cache, capfd, capfdbinary, caplog, capsys, capsysbinary, doctest_namespace, monkeypatch, optimized_finder, original_finder, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory
> >       use 'pytest --fixtures [testpath]' for help on them.
> ```

@daud99 try installing ersilia with the test extra again. This has been updated as a requirement in the pyproject.toml.

**Comment by DhanshreeA** [comment]
@daud99 I don't understand why we rename `test/inputs` to `tests/test_inputs`? It is fine to leave it as it was. You can simply add your fixture file in that same `test/inputs` directory.

**Comment by daud99** [comment]
@adebisi4145  Thankyou

@DhanshreeA you're right. I just make it as suggested. Can you check it now!

Regards

**Review by DhanshreeA — APPROVED** [review]

**Pull request merged**
