### PR TITLE
test module updates

### PR DESCRIPTION
**Pull request by febielin**

### CODE REVIEW

**Comment by febielin** [comment]
@Gemma I see that the initial PR failed due to the pandas requirement.

I remember you mentioned possibly removing this requirement. I have made some quick changes [here](https://github.com/febielin/ersilia/blob/master/ersilia/publish/test.py) to try to mimic the functionality of the pandas .read_csv, .intersection, .columns, etc. features. Perhaps if you could help me test these changes?

I know this internship is officially over, but I would like to see this through. Please let me know if the changes following the removal of the pandas requirement works. Otherwise, I will make the necessary changes to make it work!

**Comment by GemmaTuron** [comment]
Hi @febielin 

It crashes at the end of the pipeline, though I am unsure why?
Also, it does say on top there are 5 inputs but then only give 4 results?
```
Confirming there are same number of outputs as inputs...
Number of inputs: 5
Number of outputs: 5
Number of outputs and inputs are equal!

Calculating model size...

Model Size:
KB: 3904.4755859375
MB: 3.81296443939209
GB: 0.0037235980853438377

Running the model bash script...
Executing 'bash run.sh'...
Bash execution completed!

Captured Output:
smiles	Name	sa_score
CCCOc1ccccc1-c1nc(=O)c2n[nH]nc2[nH]1	mol0	2.645370
C[C@H](NC(=O)c1sccc1OCc1ccc(Cl)cc1)c1ccccc1	mol1	2.376783
CSc1ccc2c(c1)N(CCC1CCCCN1C)c1ccccc1S2	mol2	2.942951
CC(C)N(CCCCOCC(=O)NS(C)(=O)=O)c1cnc(-c2ccccc2)c(-c2ccccc2)n1	mol3	2.658069

Captured Error:

Executing ersilia run...
Ersilia run completed!

Bash output:
 [{'sa_score': '2.645370'}, {'sa_score': '2.376783'}, {'sa_score': '2.942951'}, {'sa_score': '2.658069'}]

Ersilia output:
 [{'sa_score': '2.64537'}, {'sa_score': '2.376783'}, {'sa_score': '2.942951'}, {'sa_score': '2.658069'}]
```

**Comment by GemmaTuron** [comment]
Hi @febielin,,

Regarding the inputs, why do we test 5 inputs but only get the results of 4 inputs in the command? 

For the error, I get this message at the end of the pipeline:

```
🚨🚨🚨 Something went wrong with Ersilia 🚨🚨🚨

Error message:

list indices must be integers or slices, not str
```

**Comment by GemmaTuron** [comment]
@febielin 

Looking at your code, the problem is in these lines:
```
for column in common_columns:
                print(column)
                print(ersilia_run[column][1])
                if isinstance(ersilia_run[column][1], (float, int)) and isinstance(ersilia_run[column][1], (float, int)): 
                    if not all(self._compare_tolerance(a, b, DIFFERENCE_THRESHOLD) for a, b in zip(ersilia_run[column], bash_run[column])):
                        click.echo(BOLD + "\nBash run and Ersilia run produce inconsistent results." + RESET)
                        print("Error in the following column: ", column)
                        print(ersilia_run[column])
                        print(bash_run[column])
                        raise texc.InconsistentOutputs(self.model_id)
                elif isinstance(ersilia_run[column][1], str) and isinstance(ersilia_run[column][1], str):
                    if not all(self._compare_string_similarity(a, b, 95) for a, b in zip(ersilia_run[column], bash_run[column])):
                        click.echo(BOLD + "\nBash run and Ersilia run produce inconsistent results." + RESET)
                        print("Error in the following column: ", column)
                        print(ersilia_run[column])
                        print(bash_run[column])
                        raise texc.InconsistentOutputs(self.model_id)
                elif isinstance(ersilia_run[column][1], bool) and isinstance(ersilia_run[column][1], bool):    
                    if not ersilia_run[column].equals(bash_run[column]):
                        click.echo(BOLD + "\nBash run and Ersilia run produce inconsistent results." + RESET)
                        print("Error in the following column: ", column)
                        print(ersilia_run[column])
                        print(bash_run[column])
                        raise texc.InconsistentOutputs(self.model_id)
```

If you look at ersilia_run, you have a list of dictionaries, so it does not make sense to access it like (ersilia_run[column][1])
this is the ersilia_run printed:
`[{'sa_score': '2.786522'}, {'sa_score': '2.026240'}, {'sa_score': '1.840514'}, {'sa_score': '2.566913'}]
`

**Comment by GemmaTuron** [comment]
I propose the following:
I cannot push to your fork for some authentication issues, so please when you can have a look at my suggestion and if this is what you were trying to do, add the changes in the PR:
```
for column in common_columns:
  for i in range(len(ersilia_run)):
      if isinstance(ersilia_run[i][column], (float, int)) and isinstance(ersilia_run[i][column], (float, int)): 
          if not all(self._compare_tolerance(a, b, DIFFERENCE_THRESHOLD) for a, b in zip(ersilia_run[i][column], bash_run[i][column])):
              click.echo(BOLD + "\nBash run and Ersilia run produce inconsistent results." + RESET)
              print("Error in the following column: ", column)
              print(ersilia_run[i][column])
              print(bash_run[i][column])
              raise texc.InconsistentOutputs(self.model_id)
      elif isinstance(ersilia_run[i][column], str) and isinstance(ersilia_run[i][column], str):
          if not all(self._compare_string_similarity(a, b, 95) for a, b in zip(ersilia_run[i][column], bash_run[i][column])):
              click.echo(BOLD + "\nBash run and Ersilia run produce inconsistent results." + RESET)
              print("Error in the following column: ", column)
              print(ersilia_run[i][column])
              print(bash_run[i][column])
              raise texc.InconsistentOutputs(self.model_id)
      elif isinstance(ersilia_run[i][column], bool) and isinstance(ersilia_run[i][column], bool):    
          if not ersilia_run[i][column].equals(bash_run[i][column]):
              click.echo(BOLD + "\nBash run and Ersilia run produce inconsistent results." + RESET)
              print("Error in the following column: ", column)
              print(ersilia_run[i][column])
              print(bash_run[i][column])
              raise texc.InconsistentOutputs(self.model_id)
```

**Comment by GemmaTuron** [comment]
Also, we have moved the Fuzzywuzzy requirement to the test environment only (see setup.py)

I have identified a potential small bug in here:
```
                            if self._compare_output_strings(elem1, elem2) <= 0.95: 
                                print('output1 value:', elem1)
                                print('output2 value:', elem2)
                                raise texc.InconsistentOutputs(self.model_id)
```

Is fuzzywuzzy returning values from 0 to 1 or from 0 to 100 @pittmanriley ? In the comments you mention 100

**Comment by pittmanriley** [comment]
@GemmaTuron you are correct, I made a mistake. It returns numbers between 0 and 100, so it should be checking if the strings are <= 95. Do you need me to make this change?

**Comment by febielin** [comment]
Hi all,

I apologize for the delay in communication. I have added the changes @GemmaTuron has suggested. I have also changed the values from .95 --> 95 @pittmanriley. If either/both are able to test these changes, please let me know if this fixes the error (or if any other bugs surface)!

**Comment by GemmaTuron** [comment]
Hi @febielin and @pittmanriley,

I cannot merge the changes because there are conflicts with the `test.py`, I cannot solve them as I am unsure which changes are the right ones and which relate to older versions of the test file - @febielin you only changed the 95 and the part I indicated? I see many more differences with the file in ersilia and I don't know which ones are correct
Could you please ammend that and push the PR again? 
Thanks!

**Pull request closed without merging**
