### PR TITLE
Integrate GDI inference store with CLI

### PR DESCRIPTION
**Pull request by nicholas-kondal**
- [x] Have you followed the guidelines in our [Contribution Guide](https://github.com/ersilia-os/ersilia/blob/master/CONTRIBUTING.md)
- [ ] Have you written new tests for your core changes, as applicable?
- [ ] Have you successfully ran tests with your changes locally?

**Description**

Allow precalculations to be read from Ersilia's AWS cloud environment via https://github.com/ersilia-os/model-inference-pipeline

**Status**

- Select the source of outputs during model serving
- Upload input molecules to the cloud and retrieve ecalculations via a secure S3 download link
- Provide warnings and errors in case models and/or precalculations are not currently present in the cloud

**To do**

See https://github.com/ersilia-os/model-inference-pipeline/pull/32 for next steps

### CODE REVIEW

**Comment by miquelduranfrigola** [comment]
@DhanshreeA and @kartikey-vyas - plesae let me know when will this be ready for merge?

**Comment by kartikey-vyas** [comment]
We are ready for review here, with the IaC written in the model inference repo

**Comment by miquelduranfrigola** [comment]
@Abellegese @DhanshreeA we need to merge this PR. There are conflicts with the `api.py`, probably due to the latest changes from @Abellegese . Let's try to resolve these conflicts. Many thanks!

**Comment by DhanshreeA** [comment]
@miquelduranfrigola we have actually removed the `ersilia/cli/commands/api.py` file during the process of removing the `api` command from the CLI in favor of only keeping the `run` command. Ref: https://github.com/ersilia-os/ersilia/issues/1263

I'll remove that file from this PR, and review it. cc: @kartikey-vyas hope the inference pipeline doesn't rely on this command?

**Review by DhanshreeA — APPROVED** [review]

**Pull request merged**
