### PR TITLE
Add is_input_header negative test

### PR DESCRIPTION
**Pull request by Ann-Clawson**
Thank you for taking your time to contribute to Ersilia, just a few checks before we proceed
- [X] Have you followed the guidelines in our [Contribution Guide](https://github.com/ersilia-os/ersilia/blob/master/CONTRIBUTING.md)
- [X] Have you written new tests for your core changes, as applicable?
- [X] Have you successfully ran tests with your changes locally?

**Description**

Add a CompoundIdentifier class test `test_is_input_header_negative` in `test/test_compound_identifier.py` which I noticed was created in a previous open pull request for `test_is_input_header_positive`.

**Changes to be made**

**Status**

- Implemented `test_is_input_header_negative` in `test/test_compound_identifier.py`
- Tested the code locally with `pytest` and passed

**To do**

Is this pull request related to any open issue? If yes, replace issueID below with the issue ID

Related to [#1319](https://github.com/ersilia-os/ersilia/issues/1319)

### CODE REVIEW

**Comment by Ann-Clawson** [comment]
Oh! I forgot to add in the "Description" section of the PR that I also added a `requirements.txt` file to streamline the installation of dependencies.

**Comment by dzumii** [comment]
@Ann-Clawson Thank you so much for contributing to Ersilia but this issue is specifically for current Outreachy contributors.

**Comment by DhanshreeA** [comment]
@Ann-Clawson as @dzumii mentioned we're currently not accepting contributions from anyone other than Outreachy applicants. If your PR is towards Hacktoberfest, I will have to request you to check out other participating projects. Thank you!

**Comment by Ann-Clawson** [comment]
Oh! I found this repository on [For Good First Issue](https://forgoodfirstissue.github.com/). I'm a mid-life career changer and entry-level dev seeking opportunities to get a foot in the door of the tech world (I'm currently learning how to write unit tests 🙃). Thank you for your response, I was unaware of Outreachy and will keep an eye out for May cohort applications!

**Pull request closed without merging**
