### PR TITLE
Added a standard README file 

### PR DESCRIPTION
**Pull request by arushi2715**
This is the PR for issue [11](https://github.com/ersilia-os/ersilia/issues/11).
Added a more standard README file with the necessary **installation steps** and explaining the **models**. Added a picture of the **Ersilia model** to increase the engagement of the reader.
Also, created a new folder named Documentation and added my README under it as `README_name`, since earlier there existed a file as documentation and not a folder.
@miquelduranfrigola @GemmaTuron can you look into this and tell me what more modifications need to be done.

### CODE REVIEW

**Review by GemmaTuron — CHANGES_REQUESTED** [review]
Hello @arushi2715 

Thanks for the README file. Please, to avoid downstream conflicts can you add your readme to the /documentation folder, not /Documentation?
It is good github practice to use always lowercase, as it is case-sensitive

**Comment by miquelduranfrigola** [comment]
@GemmaTuron what is the current status of this? Feel free to merge the PR at any time.

**Comment by arushi2715** [comment]
> Hello @arushi2715
> 
> Thanks for the README file. Please, to avoid downstream conflicts can you add your readme to the /documentation folder, not /Documentation? It is good github practice to use always lowercase, as it is case-sensitive

Hey @GemmaTuron I have changed the file location as specified by you.

**Review by GemmaTuron — APPROVED** [review]
Hello @arushi2715 

Thanks for your contribution, we aim to provide feedback on all these over the weekend and give next steps!

**Pull request merged**
