### PR TITLE
Modified the time tracking method to accurately track time taken

### PR DESCRIPTION
**Pull request by Malikbadmus**
**Description**

The time tracking method in use does not accurately depicts the time taken in a model run

**Changes made**

- Introduce an `update_total_time` method in `tracking.py` to get an accurate measure of time across the two (2) process, minus the time spent waiting for user input(for the CLI).
- Track time in `serve.py`.
- Track time in `run.py`.

**Status**

- A time value that reflects and depicts the total time taken for our model to run.

Related to #1090

### CODE REVIEW

**Comment by Malikbadmus** [comment]
@DhanshreeA , how the session file looks like with the changes.

[2024-06-26_22-35-59.txt](https://github.com/user-attachments/files/15996410/2024-06-26_22-35-59.txt)

**Comment by DhanshreeA** [comment]
> **Description**
> 
> The time tracking method in use does not accurately depicts the time taken in a model run
> 
> **Changes made**
> 
>     * Introduce an `update_total_time` method in `tracking.py` to get an accurate measure of time across the two (2) process, minus the time spent waiting for user input(for the CLI).
> 
>     * Track time in `serve.py`.
> 
>     * Track time in `run.py`.
> 
> 
> **Status**
> 
>     * A time value that reflects and depicts the total time taken for our model to run.
> 
> 
> Related to #1090

I'm a bit confused, how do you think the current implementation does not correctly reflect the time taken?

**Comment by Malikbadmus** [comment]
> > **Description**
> > The time tracking method in use does not accurately depicts the time taken in a model run
> > **Changes made**
> > ```
> > * Introduce an `update_total_time` method in `tracking.py` to get an accurate measure of time across the two (2) process, minus the time spent waiting for user input(for the CLI).
> > 
> > * Track time in `serve.py`.
> > 
> > * Track time in `run.py`.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > **Status**
> > ```
> > * A time value that reflects and depicts the total time taken for our model to run.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Related to #1090
> 
> I'm a bit confused, how do you think the current implementation does not correctly reflect the time taken?

I noticed while running test yesterday, i believe the time taken value we are interested in is the time taken to run a model, but we are only tracking the time used in the track method which does not reflect this, we are always getting nanoseconds even when the models take longer to serve and run.

**Comment by DhanshreeA** [comment]
LGTM!

**Pull request merged**
