### PR TITLE
Enable Ersilia to serve multiple models simultaneously

### PR DESCRIPTION
**Pull request by DhanshreeA**
Thank you for taking your time to contribute to Ersilia, just a few checks before we proceed
- [x] Have you followed the guidelines in our [Contribution Guide](https://github.com/ersilia-os/ersilia/blob/master/CONTRIBUTING.md)
- [x] Have you written new tests for your core changes, as applicable?
- [x] Have you successfully ran tests with your changes locally?

**Description**

_Replace this line with a short description here..._

**Changes to be made**

_Replace this line with how do you intend to go about getting this done..._

**Status**

_Replace this line with what you have done so far..._

**To do**

_If this is a work in progress, Replace this line with your next steps_

Is this pull request related to any open issue? If yes, replace issueID below with the issue ID

Related to #<issueID>

### CODE REVIEW

**Review by miquelduranfrigola — APPROVED** [review]
This looks good to me.

**Comment by miquelduranfrigola** [comment]
Hi @DhanshreeA the Run PyTest test failed. I have not merged.

**Comment by miquelduranfrigola** [comment]
Feel free to merge anytime

**Review by miquelduranfrigola — APPROVED** [review]
Is there a reason why we should experience permission errors? I believe this has happened before? One option would be to grant write permissions to any user when we create those folders. However, I am OK with the current solution.

**Comment by miquelduranfrigola** [comment]
Hi @DhanshreeA it doesn't seem to work now based on the checks above

**Comment by DhanshreeA** [comment]
> Hi @DhanshreeA it doesn't seem to work now based on the checks above

Hey @miquelduranfrigola - I've just pushed a fix for it.

**Pull request merged**
