### PR TITLE
Optimize Ersilia Dockerfile

### PR DESCRIPTION
**Pull request by honeyankit**
## Context

To make the Dockerfile more efficient and produce smaller images

## Approach

- [ ] Install required packages only.
- [ ] Removed all the package cache (apt) after installation.
- [ ] Removed adding unwanted scripts.
- [ ] Made code more cleaner to look.

### CODE REVIEW

**Comment by miquelduranfrigola** [comment]
Hello @honeyankit - I made some changes in the `dockerfiles` folder structures that may cause conflicts here. May I ask what is the current status of this draft pull request? Thanks!

**Comment by GemmaTuron** [comment]
Hi @honeyankit and @miquelduranfrigola 

Can we close this draft?

**Comment by honeyankit** [comment]
@GemmaTuron : I am planning to look at this PR during this week and close it out. I will resolve the conflict as well.

**Comment by honeyankit** [comment]
This PR is no longer required as I can see @miquelduranfrigola has already did the work in creating ersilia OS base image, hence closing it.

**Pull request closed without merging**
