### PR TITLE
add streamlit app ersilia-app.py

### PR DESCRIPTION
**Pull request by Amna-28**
I have created a simple streamlit app as suggested in issue #126
It has multi-page view that could be used to extend its functionality. 
Right now user can choose a model and perform predict and calculate operations on the given input string and display the output.
It also shows the representation of the molecular structure of the input using the rdkit python library as suggested by @GemmaTuron 
I would love to hear your feedback and work on your suggestions. 

image

### CODE REVIEW

**Comment by miquelduranfrigola** [comment]
Hi, @Amna-28 this is quite nice! Please see my suggestions in #126 
I am happy to accept your PR as is. So please do not implement these changes if you do not have time at the moment :)
Just let me know

**Comment by Amna-28** [comment]
Hi @miquelduranfrigola 
Keeping your suggestions in mind, I have made changes and commited those changes to the branch.
Now it shows buttons for api supported by the model that is selected from the drop-down. Please have a look at the screenshots

Capture4
Capture5

**Comment by miquelduranfrigola** [comment]
This is quite amazing, @Amna-28, well done!

A few things:
* May I request that you place these files under `ersilia/app/contrib/`?
* Can we round the output to 3 decimals?

**Comment by Amna-28** [comment]
Thank you @miquelduranfrigola ,
Yes sure I will do that.

**Comment by Amna-28** [comment]
Hi @miquelduranfrigola , I see a problem in my app, the models that user can choose from the drop-down are hard coded right now. I want to make use of the class `ModelCatalog` so that we will have the models available in the local machine in the drop down. 
What do you think?

**Comment by Amna-28** [comment]
Hi @miquelduranfrigola 
I have made following changes:

- placed all the files related to ersilia app under `ersilia/app/contrib/`
- round the output to 3 decimals
- Modified the drop-down code to include all the models that are available at local machine using `local()` method from `ModelCatalog` class.

**Comment by miquelduranfrigola** [comment]
Amazing contribution, @Amna-28 ! I am very impressed. I am merging your PR right away. No need to work on this anymore at this stage. Many thanks!

**Review by miquelduranfrigola — APPROVED** [review]
Fantastic first contribution producing a Streamlit App for chemistry models

**Comment by Amna-28** [comment]
> 

Thank you very much @miquelduranfrigola, means a lot.

**Pull request merged**
